allowBuilds:
  '@parcel/watcher': true
  esbuild: true
minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.102.5'
  - '@tanstack/query-devtools@5.102.5'
  - '@tanstack/query-persist-client-core@5.102.5'
  - '@tanstack/svelte-query-devtools@6.1.45'
  - '@tanstack/svelte-query-persist-client@6.1.45'
  - '@tanstack/svelte-query@6.1.45'
